### ISSUE TITLE
es6

### ISSUE THREAD

**Issue by timini** [graphile/bootstrap-react-apollo#1]
Hi I realise you haven't even finished this yet but is there any plan to support ES6 / babel for the server? It would be nice to have continuity with create-react-app settings.

**Comment by benjie** [comment]
This is written in ES2018 (ES9); there's no need for Babel - Node.js natively supports async/await, object rest/spread, all the new helpers, etc. Check out https://node.green/

_Pauses to think..._

Ohhhh I guess you want ES6 *modules*? I'm not keen to add a compilation step merely to use `import` statements rather than `require`; but I have been considering moving this example to using TypeScript... 🤔

**Comment by timini** [comment]
> Ohhhh I guess you want ES6 modules?

Yep, I guess so, Indeed its just sugar I can live without.  My suggestion stems from the fact I'm using create-react-app for all my projects and it would be nice to have continuity with that, but I guess its best to choose the right tools for the right purpose.  I don't have much experience with TypeScript myself... yet :(

**Comment by benjie** [comment]
Totally understand the desire for consistency 👍 I'm aiming to try and make this fairly light/universal; but hopefully you can convert it to imports using codemods.
