### ISSUE TITLE
[Question] Why not use create-react-app for client ?

### ISSUE THREAD

**Issue by jptissot** [graphile/bootstrap-react-apollo#2]
It would simplify the configuration you have to maintain. Any reason why it's ejected ?

**Comment by benjie** [comment]
Primarily because of hot loading IIRC. Also because CRA expects to live at the root of the repo, whereas we want it in a subfolder.

**Comment by jptissot** [comment]
I would argue that this will defer people from using this boilerplate. Ejecting should be up to the user of the boilerplate, not by default. 

Also, why is the client living in a subfolder ? I personally prefer it the other way around, the client (in dev) proxies the API requests using the built in proxy support of create-react-app.

**Comment by jptissot** [comment]
Thanks for this boilerplate btw :)

**Comment by benjie** [comment]
It’s a work in progress, following my personal preferences for setting up a PostGraphile project. The hot reloading is a must-have for me, but even without that I’m not planning on having CRA because I’ll be using a custom webpack config to implement persisted queries. I just grabbed it to get started quicker.

Client doing the proxying doesn’t allow for SSR, but anyway that doesn’t affect the folder layout. Ultimately each “part” will be in its own folder: server, client, worker, db, etc.

**Comment by jptissot** [comment]
Cool, for hot loading, I use https://github.com/arackaf/customize-cra. 

What are persisted queries ?

**Comment by benjie** [comment]
https://www.graphile.org/postgraphile/production/#simple-query-whitelist-persisted-queries

I’m not a fan of rewiring, or anything that reaches into node_modules and modifies things, it leads to a very fragile system IMO.
