### ISSUE TITLE
Missing `graphile-worker --once` command to install the worker schema.

### ISSUE THREAD

**Issue by metarama** [graphile/bootstrap-react-apollo#8]
Thanks to Benjie and the Postgraphile team for this awesome work. I started my journey with learning and using Postgraphile a few weeks ago.

I see that the Worker is a standalone project. And also the worker schema is included in this project also. What is the vision for worker and main graphql processes coexisting?

**Comment by benjie** [comment]
In this project is an early precursor to what became the worker project. I’ve not had time to upgrade this project to use the new worker yet, but I’d advise that you use that going forward since it actually has tests ;) Worker handles its own migrations so you can add it to an existing project; it’s also possible to move all your jobs from the old tables to the new.

**Comment by benjie** [comment]
@singingwolfboy Has added graphile-worker support to this project, so all the old worker has been ripped out. :tada:

**Comment by keithlayne** [comment]
But...the migrations have a dependency on the worker schema that I don't see managed anywhere here.  Could be handled in the setup script with graphile/worker#13 I think.  I'm using a different migration tool so I'm trying to figure out the best way to bootstrap the worker schema.  I guess that's a question for the other repo.

**Comment by benjie** [comment]
You're right; the setup script should call `graphile-worker --once` before it calls `yarn db:migrate:dev` here:

https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/scripts/setup#L196

**Comment by benjie** [comment]
I'd love a PR for this.
